### ISSUE TITLE
"Help" button crashing

### ISSUE THREAD

**Issue by mikaldl** [Bram94/NLradar#2]
When clicking on the help button, in the top right, it results in a crash:

```python
WARNING: Traceback (most recent call last):
  File "H:\Pycharm\NLradar\Python_files\nlr.py", line 3755, in helpwidget
    self.help_tabgeneral(); self.help_tabmenu(); self.help_tabkeyboard(); self.help_tabradardata(); self.help_tabproducts(); self.help_tabcolortables(); self.help_tabsettings(); self.help_tabextra()
  File "H:\Pycharm\NLradar\Python_files\nlr.py", line 3846, in help_tabkeyboard
    ['ALT+B/D/H/J/Z/W','Change radar to the one in De Bilt/Den Helder/Herwijnen/Jabbeke/Zaventem/Wideumont.'],
TypeError: list indices must be integers or slices, not tuple
```

**Comment by Bram94** [comment]
This should be solved now.
